# Linear Algebra Using NumPy

In [9]:
import numpy as np

In [10]:
A = np.array([[6, -1, 8],
              [4, 5, 9],
              [3, 5, 8]
              ])

A

array([[ 6, -1,  8],
       [ 4,  5,  9],
       [ 3,  5,  8]])

In [11]:
# calculate the rank
# using numpy's linalg sub module (linear algebra)

print('Rankg of matrix A:', np.linalg.matrix_rank(A))

Rankg of matrix A: 3


In [12]:
print('Determinant of matrix X:', np.linalg.det(A))

Determinant of matrix X: 15.000000000000007


In [14]:
A_transp = A.T
A_transp

array([[ 6,  4,  3],
       [-1,  5,  5],
       [ 8,  9,  8]])

In [15]:
# inverse of a matrix
np.linalg.inv(A)

array([[-0.33333333,  3.2       , -3.26666667],
       [-0.33333333,  1.6       , -1.46666667],
       [ 0.33333333, -2.2       ,  2.26666667]])

In [17]:
# matrix trace
np.trace(A)

19

In [18]:
# dot product
np.dot([3,4,5],
       [7,8,4])

73

In [19]:
# creating an identity matrix
id_m = np.identity(3)
id_m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# randomly generating numbers in a matrix
B = np.random.randn(2,3)
B

array([[ 0.73485088,  1.53957002,  0.3472094 ],
       [ 0.31607373, -1.81850277, -1.35608882]])

Some examples of the application of linear algebra in machine learning:
- Vectors and scalers: recommender system (Netflix recommendation) each user's preference can be represented as a large vector of ratings.
- Vector Operations (dot product): used the input vector and weight matrix is calculated in each neuron (activation)
- Matrics: data in general is represented as row-col format, which is a 2-d array 
- PCA: Principle Component Analysis: dimensionality reduction 
- Matrix Rank: used in feature selection
- Norms: used in regularization, which reduces overfitting